server:
  port: 2333
  address: 0.0.0.0
  password: "betedomingos13"
  
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0"
      repository: "https://maven.lavalink.dev/releases"
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.3.0"
      repository: "https://jitpack.io"

plugins:
  sources:
    spotify: true
    apple-music: false
    deezer: false
    yandex-music: false
    flowery-tts: false

leecher: {}

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    max-history: 30
  level:
    root: INFO
    lavalink: INFO