server:
  port: 2333
  address: 0.0.0.0
lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.11.0"
      repository: "https://maven.lavalink.dev/releases"
  server:
    password: "betedomingos13"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
      local: false
logging:
  file:
    max-history: 30
  level:
    root: INFO
    lavalink: INFO